title: Bulk RNA-seq quantification (2025)
description: A tutorial for the quantification analysis from bulk RNA-seq data
theme: just-the-docs

url: https://jyyulab.github.io/bulkRNAseq_quantification_pipeline/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
